### ISSUE TITLE
Fix linting issues

### ISSUE THREAD

**Issue by nanxstats** [nanxstats/awesome-webr#5]
See awesome-lint workflow results.

**Comment by nanxstats** [comment]
Hey @mcanouil After a few tries, I had to remove the awesome-lint workflow in https://github.com/nanxstats/awesome-webr/commit/110d79811808fc642b775033616d4f2e1c895942 as it has compatibility issues with the TOC generated by the VS Code extension "Markdown All in One", which uses a special `<!-- omit in toc -->` comment after the heading, and this heading with the extra comment cannot be identified as the TOC heading by the linter.

I'm sure this workflow is super helpful and has helped identifying a few style issues (fixed in https://github.com/nanxstats/awesome-webr/commit/c63d76353618427c8dba9ff9640ac39313029ab1), so I hope we can add it back sometime.

**Comment by mcanouil** [comment]
Oh, yes indeed, I have some workspace settings for this:!<https://github.com/mcanouil/awesome-quarto/blob/main/.vscode/settings.json> (I did not add it because I wasn't sure if you were using VSCode and the "markdown all in one" extension, especially because there is an Rproj file which is an RStudio IDE thing).

Additionally, you can take a look at my list: <https://github.com/mcanouil/awesome-quarto/blob/main/README.md>.

**Comment by nanxstats** [comment]
@mcanouil Thanks so much for the hint! I should have read the extension's documentation better... In any case, I've added the settings in https://github.com/nanxstats/awesome-webr/commit/7c04f2c6cdcbaab5d341207516ec8f9512fad216 and added back the awesome-lint workflow in https://github.com/nanxstats/awesome-webr/commit/206cad19860bcc7f7b7c00c8ee546ab8e650e1e5.
